chain_width = 80
empty_item_single_line = true
enum_discrim_align_threshold = 40
format_strings = true
imports_granularity = "Crate" 
imports_indent = "Block"
imports_layout = "HorizontalVertical"
max_width = 90
normalize_comments = true
reorder_imports = true
struct_field_align_threshold = 40
struct_lit_single_line = true
tab_spaces = 4 
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
fn_single_line = true
signle_line_if_else_max_width = 65
